[package]
name = "webhook-server"
version = "0.1.0"
authors = ["Arne Beer <arne@twobeer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "1", features = ["ssl"] }
actix = "0.8"
handlebars = "2.0"
openssl = "0.10"
chrono = { version = "0.4", features = ["serde"] }

config = "0.9"
log = "0.4"
simplelog = "0.7"

subprocess = "0.1"
shellexpand = "1"

serde = "1"
serde_yaml = "0.8"
serde_json = "1"
hex = "0.4"

hmac = "0.7"
sha-1 = "0.8"
futures = "0.1"

base64 = "0.10"
