name: Packaging

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This should work with only the `include`s but it currently doesn't because of this bug:
        # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: webhookserver
            release_name: webhookserver-linux-amd64
          - os: windows-latest
            artifact_name: webhookserver.exe
            release_name: webhookserver-windows-amd64.exe
          - os: macos-latest
            artifact_name: webhookserver
            release_name: webhookserver-macos-amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --locked

    - name: Compress client
      uses: svenstaro/upx-action@v2
      with:
        file: target/release/${{ matrix.artifact_name }}
        args: --lzma
        strip: true

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.release_name }}
        tag: ${{ github.ref }}
