name: Webhook server tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
